DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;

CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(3) NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO),
    CONSTRAINT CK_STUDENT CHECK(STU_AGE BETWEEN 0 AND 100)
);

CREATE TABLE SUBJECT(
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(20 BYTE) NOT NULL,
    SUB_PROFESSOR VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
);

CREATE TABLE ENROLL(
    ENR_NO NUMBER(2) NOT NULL,
    STU_NO CHAR(5 BYTE) NOT NULL,
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO),
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)
);